/**
 * Generates src/shared/theme-tokens.ts from the Tlapalli theme system.
 *
 * Tlapalli is MIT-licensed (see NOTICE). The generated file is committed, so
 * builds need no network. Re-run this script only when the upstream theme
 * changes:  node scripts/build-theme-tokens.ts
 */

import fs from "node:fs";
import path from "node:path";

const BASE = "https://raw.githubusercontent.com/ackzell/tlapalli-vscode-theme/main/themes/";

const SLUGS = [
  "obsidian",
  "gold",
  "turquoise",
  "quartz",
  "lapis-lazuli",
  "amethyst",
  "jade",
  "fire-opal",
] as const;

/** CSS variable -> ordered candidate VSCode color keys. */
const ROLE_KEYS: Record<string, string[]> = {
  "--tb-bg": ["editor.background"],
  "--tb-bg-elevated": ["editorWidget.background", "editor.background"],
  "--tb-surface": ["button.background", "badge.background", "editorWidget.background"],
  "--tb-fg": ["editor.foreground"],
  "--tb-fg-muted": ["descriptionForeground", "editor.foreground"],
  "--tb-fg-subtle": ["editorLineNumber.foreground", "descriptionForeground"],
  "--tb-border": ["panel.border", "sideBar.border", "editorGroup.border"],
  "--tb-accent": ["textLink.foreground", "editor.foreground"],
  "--tb-signature": ["activityBarBadge.background", "button.background"],
  "--tb-selection": ["editor.selectionBackground"],
  "--tb-hover": ["list.hoverBackground", "editor.selectionBackground"],
  "--tb-error": ["list.errorForeground", "errorForeground"],
  "--tb-progress": ["progressBar.background", "activityBarBadge.background"],
};

type Colors = Record<string, string>;

async function fetchTheme(file: string): Promise<Colors> {
  const res = await fetch(`${BASE}${file}`, { redirect: "follow" });
  if (!res.ok) throw new Error(`Failed to fetch ${file}: ${res.status}`);
  const json = (await res.json()) as { colors?: Colors };
  return json.colors ?? {};
}

function pick(colors: Colors, keys: string[]): string {
  for (const key of keys) {
    const value = colors[key];
    if (typeof value === "string" && value.startsWith("#")) return value;
  }
  return "#000000";
}

/**
 * Blends `from` toward `to` by `ratio`, preserving any 8-digit alpha. Used to
 * make the raw line-number color legible as shell UI text.
 */
function blend(from: string, to: string, ratio: number): string {
  const parse = (hex: string): [number, number, number, number] => {
    const raw = hex.replace("#", "");
    const alpha = raw.length === 8 ? parseInt(raw.slice(6, 8), 16) : 255;
    return [
      parseInt(raw.slice(0, 2), 16),
      parseInt(raw.slice(2, 4), 16),
      parseInt(raw.slice(4, 6), 16),
      alpha,
    ];
  };
  const a = parse(from);
  const b = parse(to);
  const channel = (index: number): string =>
    Math.round(a[index] + (b[index] - a[index]) * ratio)
      .toString(16)
      .padStart(2, "0");
  const alpha = Math.round(a[3] + (b[3] - a[3]) * ratio);
  const rgb = `#${channel(0)}${channel(1)}${channel(2)}`;
  return alpha === 255 ? rgb : `${rgb}${alpha.toString(16).padStart(2, "0")}`;
}

/**
 * How far `--tb-fg-subtle` is pulled toward `--tb-fg`. The raw
 * `editorLineNumber.foreground` is nearly invisible against the shell
 * background, so we blend it toward the foreground: brighter in dark modes,
 * darker in light modes, still dimmer than `--tb-fg-muted`.
 */
const SUBTLE_FG_MIX = 0.15;

function tokensFor(colors: Colors): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [cssVar, keys] of Object.entries(ROLE_KEYS)) out[cssVar] = pick(colors, keys);
  out["--tb-fg-subtle"] = blend(out["--tb-fg-subtle"], out["--tb-fg"], SUBTLE_FG_MIX);
  return out;
}

async function main(): Promise<void> {
  const variants: Record<string, { dark: Record<string, string>; light: Record<string, string> }> =
    {};

  for (const slug of SLUGS) {
    const [dark, light] = await Promise.all([
      fetchTheme(`tlapalli-${slug}-theme.json`),
      fetchTheme(`tlapalli-${slug}-light-theme.json`),
    ]);
    variants[slug] = { dark: tokensFor(dark), light: tokensFor(light) };
    process.stdout.write(`  ${slug}: ok\n`);
  }

  const banner =
    "// GENERATED by scripts/build-theme-tokens.ts — do not edit by hand.\n" +
    "// Color values derived from the Tlapalli theme (MIT); see NOTICE.\n\n";

  const body =
    `export const TLAPALLI_TOKENS = ${JSON.stringify(variants, null, 2)} as const\n\n` +
    `export const TLAPALLI_VARIANTS = ${JSON.stringify(SLUGS, null, 2)} as const\n\n` +
    `export type TlapalliVariant = (typeof TLAPALLI_VARIANTS)[number]\n`;

  const here = import.meta.dirname ?? process.cwd();
  const target = path.resolve(here, "../src/shared/theme-tokens.ts");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, banner + body);
  process.stdout.write(`wrote ${path.relative(process.cwd(), target)}\n`);
}

main().catch((error) => {
  process.stderr.write(`${String(error)}\n`);
  process.exit(1);
});
